### ISSUE TITLE
Cuando la lista de notas esta vacia, al clickear en eliminar se rompe todo

### ISSUE THREAD

**Issue by bruno211282** [bruno211282/curpy#9]
Cuando la lista de notas esta vacia, al clickear en eliminar se rompe todo.
Habria que "deshabilitar el boton" cuando no hay ningun elemento de la lista seleccionado. O deshabilitarlo siempre y solo habilitarlo al seleccionar un elemento.

**Comment by fmazzucco** [comment]
Se subió directamente a `master`
